name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t sample-app:vuln ./sample-app

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: sample-app:vuln
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

